<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/d/db/Logo_ITESO_normal.jpg" width="150px" height="90px" />

## Ciencia de Datos e Inteligencia de Negocios

### Proyecto Final.- Insurance.

>##### Carlos Cuevas
>##### Mateo Verea
>##### Oscar Villa

### Objetivo:

Dada la base da datos, se definirán métricas para analizar el desempeño de agentes de seguros basado en diferentes atributos, como la demografía, preductos vendidos, zona, etc. Con la finalidad de mejorar el conocimiento existente y que se utiliza para la segmentación de agentes bajo un sistema de predicción supervisado.

In [5]:
#Importar librerías necesarias.
import random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.optimize as opt
from mylib import mylib
from sklearn import svm
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from sklearn.metrics import (confusion_matrix,precision_score,recall_score,f1_score,accuracy_score)

In [4]:
#Database asignada
data = pd.read_csv('finalapi.csv')
data.head()

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,RETENTION_POLY_QTY,POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,NB_WRTN_PREM_AMT,...,PL_BOUND_CT_ELINKS,PL_QUO_CT_ELINKS,PL_BOUND_CT_PLRANK,PL_QUO_CT_PLRANK,PL_BOUND_CT_eQTte,PL_QUO_CT_eQTte,PL_BOUND_CT_APPLIED,PL_QUO_CT_APPLIED,PL_BOUND_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW
0,3,3,BOILERMACH,CL,IN,2005,0,0,0,40.0,...,0,0,0,103,50,288,0,0,0,0
1,3,3,BOILERMACH,CL,IN,2006,0,0,0,151.0,...,0,0,0,103,50,288,0,0,0,0
2,3,3,BOILERMACH,CL,IN,2007,0,0,0,40.0,...,0,0,0,103,50,288,0,0,0,0
3,3,3,BOILERMACH,CL,IN,2008,0,0,0,69.0,...,0,0,0,103,50,288,0,0,0,0
4,3,3,BOILERMACH,CL,IN,2009,0,0,0,28.0,...,0,0,0,103,50,288,0,0,0,0

In [6]:
reporte=mylib.dqr(data)
reporte

,Nombres,Data_Types,Missing_Values,Present_Values,Unique_Values,Min,Max
AGENCY_ID,AGENCY_ID,int64,0,213328,1623,3,9998
PRIMARY_AGENCY_ID,PRIMARY_AGENCY_ID,int64,0,213328,588,3,99999
PROD_ABBR,PROD_ABBR,object,0,213328,28,ANNIV,YACHT
PROD_LINE,PROD_LINE,object,0,213328,2,CL,PL
STATE_ABBR,STATE_ABBR,object,0,213328,6,IN,WV
STAT_PROFILE_DATE_YEAR,STAT_PROFILE_DATE_YEAR,int64,0,213328,11,2005,2015
RETENTION_POLY_QTY,RETENTION_POLY_QTY,int64,0,213328,4952,0,21979
POLY_INFORCE_QTY,POLY_INFORCE_QTY,int64,0,213328,5190,0,22968
PREV_POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,int64,0,213328,5327,0,99999
NB_WRTN_PREM_AMT,NB_WRTN_PREM_AMT,float64,0,213328,36088,0,556930
WRTN_PREM_AMT,WRTN_PREM_AMT,float64,0,213328,117534,-202778,1.71574e+06
PREV_WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,float64,0,213328,115623,-186181,1.90457e+06
PRD_ERND_PREM_AMT,PRD_ERND_PREM_AMT,float64,0,213328,148184,-164349,1.7805e+06
PRD_INCRD_LOSSES_AMT,PRD_INCRD_LOSSES_AMT,float64,0,213328,49400,-5e+06,6.24123e+06
MONTHS,MONTHS,int64,0,213328,12,1,12
RETENTION_RATIO,RETENTION_RATIO,float64,0,213328,21377,0,99999
LOSS_RATIO,LOSS_RATIO,float64,0,213328,53126,-756.229,99999
LOSS_RATIO_3YR,LOSS_RATIO_3YR,float64,0,213328,14485,-7215.01,99999
GROWTH_RATE_3YR,GROWTH_RATE_3YR,float64,0,213328,11050,-1,99999
AGENCY_APPOINTMENT_YEAR,AGENCY_APPOINTMENT_YEAR,int64,0,213328,74,1935,99999
ACTIVE_PRODUCERS,ACTIVE_PRODUCERS,int64,0,213328,98,1,99999
MAX_AGE,MAX_AGE,int64,0,213328,61,38,99999
MIN_AGE,MIN_AGE,int64,0,213328,70,11,99999
VENDOR_IND,VENDOR_IND,object,0,213328,2,N,Y
VENDOR,VENDOR,object,0,213328,10,A,Unknown
PL_START_YEAR,PL_START_YEAR,int64,0,213328,23,1994,99999
PL_END_YEAR,PL_END_YEAR,int64,0,213328,10,2004,99999
COMMISIONS_START_YEAR,COMMISIONS_START_YEAR,int64,0,213328,14,2003,99999
COMMISIONS_END_YEAR,COMMISIONS_END_YEAR,int64,0,213328,11,2003,99999
CL_START_YEAR,CL_START_YEAR,int64,0,213328,6,2011,99999
CL_END_YEAR,CL_END_YEAR,int64,0,213328,6,2011,99999
ACTIVITY_NOTES_START_YEAR,ACTIVITY_NOTES_START_YEAR,int64,0,213328,4,2013,99999
ACTIVITY_NOTES_END_YEAR,ACTIVITY_NOTES_END_YEAR,int64,0,213328,3,2014,99999
CL_BOUND_CT_MDS,CL_BOUND_CT_MDS,int64,0,213328,16,0,99999
CL_QUO_CT_MDS,CL_QUO_CT_MDS,int64,0,213328,36,0,99999
CL_BOUND_CT_SBZ,CL_BOUND_CT_SBZ,int64,0,213328,24,0,99999
CL_QUO_CT_SBZ,CL_QUO_CT_SBZ,int64,0,213328,30,0,99999
CL_BOUND_CT_eQT,CL_BOUND_CT_eQT,int64,0,213328,20,0,99999
CL_QUO_CT_eQT,CL_QUO_CT_eQT,int64,0,213328,24,0,99999
PL_BOUND_CT_ELINKS,PL_BOUND_CT_ELINKS,int64,0,213328,31,0,99999
PL_QUO_CT_ELINKS,PL_QUO_CT_ELINKS,int64,0,213328,90,0,99999
PL_BOUND_CT_PLRANK,PL_BOUND_CT_PLRANK,int64,0,213328,60,0,99999
PL_QUO_CT_PLRANK,PL_QUO_CT_PLRANK,int64,0,213328,179,0,99999
PL_BOUND_CT_eQTte,PL_BOUND_CT_eQTte,int64,0,213328,160,0,99999
PL_QUO_CT_eQTte,PL_QUO_CT_eQTte,int64,0,213328,358,0,99999
PL_BOUND_CT_APPLIED,PL_BOUND_CT_APPLIED,int64,0,213328,22,0,99999
PL_QUO_CT_APPLIED,PL_QUO_CT_APPLIED,int64,0,213328,40,0,99999
PL_BOUND_CT_TRANSACTNOW,PL_BOUND_CT_TRANSACTNOW,int64,0,213328,5,0,99999
PL_QUO_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW,int64,0,213328,11,0,99999